# Generated by Django 5.1.6 on 2025-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(0, "Low"), (1, "Medium"), (2, "High")], default=0
            ),
        ),
    ]
